### PR TITLE
Updated for Java 8u131

### PR DESCRIPTION
**Pull request by dbenz04**

### CODE REVIEW

**Review by proudcanadianeh — COMMENTED** [review]
This looks great, thanks! I am just going to test this against a number of machines just to be overly cautious though.

**Comment by proudcanadianeh** [comment]
Hmmm. Installing and upgrading is working fine, but upon uninstall I get a failure with an error "String cannot be of zero length".

Are you seeing this as well?

**Comment by dbenz04** [comment]
I didn't test the uninstall, and won't be able to until tomorrow. Feel free to make whatever changes are necessary to make it work.

Thanks,
Dave


-------- Original Message --------

**Comment by dbenz04** [comment]
I just updated the version number in the uninstall script - I didn't notice that was there previously. Uninstalls should work now.

**Comment by proudcanadianeh** [comment]
Ok, your changes are submitted for approval on chocolatey. Now I just have to figure out how to manage this part.... (Still very new to Github)

**Pull request merged**
